bind c new-window

# Vim style pane selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Use Alt-vim keys without prefix key to switch panes
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Shift arrow to switch windows
bind  -n S-left previous-window 
bind  -n S-right next-window

# Enable mouse control (clickable windows, panes, resizable panes)
# Enable mouse mode (tmux 2.1 and above
set -g mouse on
# set -g mouse-select-window on
# set -g mouse-select-pane on
# set -g mouse-resize-pane oj

# reload config file (change file location to your the tmux.conf you want to use)
unbind r

new -s my_sess # create new session
# neww -n shell # create new window
split-window -h
split-window -v
# split-window -t shell # split vertically the window just created

# for neovim
set -g @resurrect-strategy-nvim 'session'
set-option -g @resurrect-processes '.*nvim.*'
set-option -g @resurrect-processes '.LunarVim.*'
set-option -g @resurrect-processes '.lvim.*
set-option -g @resurrect-processes '.vim.*

## List of plugins

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'dracula/tmux'


# dracula customizations
set -g @dracula-plugins "time"
set -g @dracula-show-powerline true
set -g @dracula-show-celcius true 
set -g @dracula-military-time true


# Other examples:
# set -g @plugin 'github_username/plugin_name'
# r set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@bitbucket.com:user/plugin'
# set -g @plugin 'git@github.com:user/plugin'

bind r source-file ~/.tmux.conf \; display "Reloaded tmux config"
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
